builds:
- binary: muiblok
  env:
  - CGO_ENABLED=0
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - '(?i)\breadme\b'
    - '(?i)\bsmall\b'
brews:
  -
    name: muiblok
    github:
      owner: apjames93
      name: homebrew-muiblok
    commit_author:
      name: goreleaserbot
      email: goreleaser@carlosbecker.com
    description: "https://github.com/apjames93/mui-storyblok-cli"
    dependencies:
      - git
      - zsh
    install: |
      bin.install "muiblok"